import { Inter } from "next/font/google";
import "./globals.css";
import LayoutComponent from "../components/Layout/Layout";
import { AuthUserProvider } from "./AuthProvider";
import { PropsWithChildren } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <AuthUserProvider>
          <LayoutComponent>{children}</LayoutComponent>
        </AuthUserProvider>
      </body>
    </html>
  );
}
